import type { Metadata } from "next";
import ThemeRegistry from "@/components/theme-registry/theme.registry";
import "@/styles/app.css";
import NprogressWrapper from "@/lib/nprogress.wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", // hoặc '/favicon.png'
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <NprogressWrapper>{children}</NprogressWrapper>
        </ThemeRegistry>
      </body>
    </html>
  );
}
